/// disclaimer: this file is generated by AI.
#pragma once

#include "frontend/ast/ast.hpp"
#include "frontend/syntax/error.hpp"
#include "utils/diagnosis.hpp"

#include <CACTBaseVisitor.h>
#include <CACTLexer.h>
#include <CACTParser.h>
#include <any>
#include <memory>
#include <string>
#include <utility>

class ASTVisitor : public CACTBaseVisitor {
public:
    template <typename T> using node_ptr = std::shared_ptr<T>;

    template <typename T> static std::any wrap(T&& val) {
        return std::make_any<node_ptr<T>>(std::make_shared<T>(std::forward<T>(val)));
    }

private:
    static Location get_loc(antlr4::ParserRuleContext* ctx) {
        if (!ctx || !ctx->start) return {};
        return {static_cast<int>(ctx->start->getLine()),
                static_cast<int>(ctx->start->getCharPositionInLine())};
    }

    static Location get_loc(antlr4::tree::TerminalNode* node) {
        if (!node || !node->getSymbol()) return {};
        return {static_cast<int>(node->getSymbol()->getLine()),
                static_cast<int>(node->getSymbol()->getCharPositionInLine())};
    }

    static Location get_loc(antlr4::tree::ParseTree* node) {
        if (!node) return {};
        if (auto* ctx = dynamic_cast<antlr4::ParserRuleContext*>(node)) return get_loc(ctx);
        if (auto* term = dynamic_cast<antlr4::tree::TerminalNode*>(node)) return get_loc(term);
        return {};
    }

public:
    template <typename T> static T take(std::any a) {
        if (a.type() == typeid(node_ptr<T>)) {
            return std::move(*std::any_cast<node_ptr<T>>(a));
        }
        throw COMPILER_ERROR_T(fmt::format("take failed for type {}", typeid(T).name()),
                               "ast-gen error");
    }

    std::any visitCompUnit(CACTParser::CompUnitContext* ctx) override {
        auto loc = get_loc(ctx);
        auto items = std::vector<ast::CompUnit::Item>{};
        for (auto* child : ctx->children) {
            auto res = visit(child);
            if (res.has_value()) {
                if (res.type() == typeid(node_ptr<ast::Decl>)) {
                    items.emplace_back(take<ast::Decl>(res));
                } else if (res.type() == typeid(node_ptr<ast::FuncDef>)) {
                    items.emplace_back(take<ast::FuncDef>(res));
                }
            }
        }
        return std::make_any<ast::CompUnit*>(new ast::CompUnit(loc, std::move(items)));
    }

    std::any visitDecl(CACTParser::DeclContext* ctx) override {
        if (ctx->constDecl()) return visit(ctx->constDecl());
        if (ctx->varDecl()) return visit(ctx->varDecl());
        return {};
    }

    std::any visitConstDecl(CACTParser::ConstDeclContext* ctx) override {
        ast::ConstDecl constDecl;
        constDecl.loc = get_loc(ctx);
        constDecl.type = take<ast::Type>(visit(ctx->basicType()));
        for (auto* constDefCtx : ctx->constDef()) {
            constDecl.defs.push_back(take<ast::ConstDef>(visit(constDefCtx)));
        }
        return wrap(ast::Decl(std::move(constDecl)));
    }

    std::any visitVarDecl(CACTParser::VarDeclContext* ctx) override {
        ast::VarDecl varDecl;
        varDecl.loc = get_loc(ctx);
        varDecl.type = take<ast::Type>(visit(ctx->basicType()));
        for (auto* varDefCtx : ctx->varDef()) {
            varDecl.defs.push_back(take<ast::VarDef>(visit(varDefCtx)));
        }
        return wrap(ast::Decl(std::move(varDecl)));
    }

    std::any visitConstDef(CACTParser::ConstDefContext* ctx) override {
        ast::ConstDef constDef;
        constDef.loc = get_loc(ctx);
        constDef.name = ctx->ID()->getText();
        for (auto* intLit : ctx->INT_LITERAL()) {
            constDef.dims.push_back(std::stoi(intLit->getText(), nullptr, 0));
        }
        constDef.val = take<ast::ConstInitVal>(visit(ctx->constInitVal()));
        return wrap(std::move(constDef));
    }

    std::any visitVarDef(CACTParser::VarDefContext* ctx) override {
        ast::VarDef varDef;
        varDef.loc = get_loc(ctx);
        varDef.name = ctx->ID()->getText();
        for (auto* intLit : ctx->INT_LITERAL()) {
            varDef.dims.push_back(std::stoi(intLit->getText(), nullptr, 0));
        }
        if (ctx->constInitVal()) {
            varDef.val = take<ast::ConstInitVal>(visit(ctx->constInitVal()));
        }
        return wrap(std::move(varDef));
    }

    std::any visitConstInitVal(CACTParser::ConstInitValContext* ctx) override {
        ast::ConstInitVal initVal;
        initVal.loc = get_loc(ctx);
        if (ctx->constExp()) {
            initVal.val = take<ast::ConstExp>(visit(ctx->constExp()));
        } else {
            std::vector<ast::ConstInitVal> vals;
            for (auto* child : ctx->constInitVal()) {
                vals.push_back(take<ast::ConstInitVal>(visit(child)));
            }
            initVal.val = std::move(vals);
        }
        return wrap(std::move(initVal));
    }

    std::any visitFuncDef(CACTParser::FuncDefContext* ctx) override {
        ast::FuncDef funcDef;
        funcDef.loc = get_loc(ctx);
        funcDef.type = take<ast::Type>(visit(ctx->funcType()));
        funcDef.name = ctx->ID()->getText();
        if (ctx->funcParams()) {
            funcDef.params = take<ast::FuncParams>(visit(ctx->funcParams()));
        }
        funcDef.block = take<ast::BlockStmt>(visit(ctx->block()));
        return wrap(std::move(funcDef));
    }

    std::any visitFuncParams(CACTParser::FuncParamsContext* ctx) override {
        ast::FuncParams params;
        for (auto* paramCtx : ctx->funcParam()) {
            params.push_back(take<ast::FuncParam>(visit(paramCtx)));
        }
        return wrap(std::move(params));
    }

    std::any visitFuncParam(CACTParser::FuncParamContext* ctx) override {
        ast::FuncParam param;
        param.loc = get_loc(ctx);
        param.type = take<ast::Type>(visit(ctx->basicType()));
        param.name = ctx->ID()->getText();
        for (auto* intLit : ctx->INT_LITERAL()) {
            param.dims.push_back(std::stoi(intLit->getText(), nullptr, 0));
        }
        if (ctx->getText().find("[]") != std::string::npos) {
            param.dims.insert(param.dims.begin(), std::nullopt);
        }
        return wrap(std::move(param));
    }

    std::any visitBlock(CACTParser::BlockContext* ctx) override {
        ast::BlockStmt block;
        block.loc = get_loc(ctx);
        for (auto* itemCtx : ctx->blockItem()) {
            block.items.push_back(take<ast::BlockStmt::Item>(visit(itemCtx)));
        }
        return wrap(std::move(block));
    }

    std::any visitBlockItem(CACTParser::BlockItemContext* ctx) override {
        if (ctx->decl()) return wrap(ast::BlockStmt::Item(take<ast::Decl>(visit(ctx->decl()))));
        if (ctx->stmt()) return wrap(ast::BlockStmt::Item(take<ast::Stmt>(visit(ctx->stmt()))));
        return {};
    }

    std::any visitBasicType(CACTParser::BasicTypeContext* ctx) override {
        if (ctx->INT()) return wrap(ast::Type::INT);
        if (ctx->BOOL()) return wrap(ast::Type::BOOL);
        if (ctx->FLOAT()) return wrap(ast::Type::FLOAT);
        if (ctx->DOUBLE()) return wrap(ast::Type::DOUBLE);
        return {};
    }

    std::any visitFuncType(CACTParser::FuncTypeContext* ctx) override {
        if (ctx->basicType()) return visit(ctx->basicType());
        if (ctx->VOID()) return wrap(ast::Type::VOID);
        return {};
    }

    std::any visitConstExp(CACTParser::ConstExpContext* ctx) override {
        // Handle optional leading unary operators in const expressions.
        // Grammar: ('+' | '-')* number | '!'* boolNumber
        if (ctx->number()) {
            auto val = take<ast::ConstExp>(visit(ctx->number()));
            // count '-' before the number to determine sign
            int sign = 1;
            for (auto* child : ctx->children) {
                if (child == ctx->number()) break;
                if (auto* term = dynamic_cast<antlr4::tree::TerminalNode*>(child)) {
                    auto t = term->getText();
                    if (t == "-") sign *= -1;
                }
            }
            if (sign == -1) {
                val = match(val, [](auto&& v) -> ast::ConstExp { return -v; });
            }
            return wrap(std::move(val));
        }
        if (ctx->boolNumber()) {
            auto val = take<ast::ConstExp>(visit(ctx->boolNumber()));
            // count '!' before the bool to determine parity
            int bangs = 0;
            for (auto* child : ctx->children) {
                if (child == ctx->boolNumber()) break;
                if (auto* term = dynamic_cast<antlr4::tree::TerminalNode*>(child)) {
                    if (term->getText() == "!") ++bangs;
                }
            }
            if (bangs % 2 == 1) {
                val = match(val, [](bool v) -> ast::ConstExp { return !v; });
            }
            return wrap(std::move(val));
        }
        return {};
    }

    std::any visitNumber(CACTParser::NumberContext* ctx) override {
        if (ctx->INT_LITERAL())
            return wrap(ast::ConstExp(std::stoi(ctx->INT_LITERAL()->getText(), nullptr, 0)));
        if (ctx->FLOAT_LITERAL())
            return wrap(ast::ConstExp(std::stof(ctx->FLOAT_LITERAL()->getText())));
        if (ctx->DOUBLE_LITERAL())
            return wrap(ast::ConstExp(std::stod(ctx->DOUBLE_LITERAL()->getText())));
        return {};
    }

    std::any visitBoolNumber(CACTParser::BoolNumberContext* ctx) override {
        return wrap(ast::ConstExp(ctx->TRUE() != nullptr));
    }

    std::any visitLVal(CACTParser::LValContext* ctx) override {
        ast::LVal lval_id;
        auto loc = get_loc(ctx);
        lval_id.loc = loc;
        lval_id.name = ctx->ID()->getText();
        if (ctx->exp().size()) {
            ast::LValExp lval{.val = lval_id};
            lval.loc = lval_id.loc;
            std::optional<ast::BinaryExp> result;
            for (auto* expCtx : ctx->exp()) {
                if (result) {
                    result = ast::BinaryExp{
                        .op = ast::BinaryOp::INDEX,
                        .left = std::move(*std::move(result)).toBoxed(),
                        .right = std::make_unique<ast::Exp>(take<ast::Exp>(visit(expCtx)))};
                    result->loc = expCtx->start ? get_loc(expCtx) : loc;
                } else {
                    auto left = ast::PrimaryExp{std::move(lval)};
                    left.loc = lval.loc;
                    result = ast::BinaryExp{
                        .op = ast::BinaryOp::INDEX,
                        .left = std::move(left).toBoxed(),
                        .right = std::make_unique<ast::Exp>(take<ast::Exp>(visit(expCtx)))};
                    result->loc = expCtx->start ? get_loc(expCtx) : loc;
                }
            }
            auto ret = ast::LValExp{.val = std::move(*result)};
            ret.loc = loc;
            return wrap(std::move(ret));
        } else {
            auto ret = ast::LValExp{.val = lval_id};
            ret.loc = loc;
            return wrap(std::move(ret));
        }
    }

    std::any visitStmt(CACTParser::StmtContext* ctx) override {
        if (ctx->lVal()) {
            ast::AssignStmt assign{.var = take<ast::LValExp>(visit(ctx->lVal())),
                                   .exp = take<ast::Exp>(visit(ctx->exp()))};
            assign.loc = get_loc(ctx);
            return wrap(ast::Stmt(std::move(assign)));
        }
        if (ctx->RETURN()) {
            ast::ReturnStmt stmt;
            stmt.loc = get_loc(ctx);
            if (ctx->exp()) {
                stmt.exp = take<ast::Exp>(visit(ctx->exp()));
            }
            return wrap(ast::Stmt(std::move(stmt)));
        }
        if (ctx->IF()) {
            ast::IfStmt ifStmt{
                .cond = take<ast::Exp>(visit(ctx->cond())),
                .stmt = std::make_unique<ast::Stmt>(take<ast::Stmt>(visit(ctx->stmt(0)))),
                .else_stmt = (ctx->ELSE())
                                 ? std::make_unique<ast::Stmt>(take<ast::Stmt>(visit(ctx->stmt(1))))
                                 : std::optional<ast::StmtBox>{}};
            ifStmt.loc = get_loc(ctx);
            return wrap(ast::Stmt(std::move(ifStmt)));
        }
        if (ctx->WHILE()) {
            ast::WhileStmt whileStmt{
                .cond = take<ast::Exp>(visit(ctx->cond())),
                .stmt = std::make_unique<ast::Stmt>(take<ast::Stmt>(visit(ctx->stmt(0))))};
            whileStmt.loc = get_loc(ctx);
            return wrap(ast::Stmt(std::move(whileStmt)));
        }
        if (ctx->BREAK()) {
            ast::BreakStmt stmt;
            stmt.loc = get_loc(ctx);
            return wrap(ast::Stmt(stmt));
        }
        if (ctx->CONTINUE()) {
            ast::ContinueStmt stmt;
            stmt.loc = get_loc(ctx);
            return wrap(ast::Stmt(stmt));
        }
        if (ctx->block()) {
            return wrap(ast::Stmt(take<ast::BlockStmt>(visit(ctx->block()))));
        }
        auto exp = take<ast::Exp>(visit(ctx->exp()));
        ast::ExpStmt stmt{.exp = std::move(exp)};
        stmt.loc = get_loc(ctx);
        return wrap(ast::Stmt(std::move(stmt)));
    }

    std::any visitExp(CACTParser::ExpContext* ctx) override {
        return visit(ctx->addExp());
    }

    std::any visitCond(CACTParser::CondContext* ctx) override {
        return visit(ctx->lOrExp());
    }

    std::any visitLOrExp(CACTParser::LOrExpContext* ctx) override {
        if (ctx->lOrExp()) {
            ast::BinaryExp bin{
                .op = ast::BinaryOp::OR,
                .left = std::make_unique<ast::Exp>(take<ast::Exp>(visit(ctx->lOrExp()))),
                .right = std::make_unique<ast::Exp>(take<ast::Exp>(visit(ctx->lAndExp())))};
            bin.loc = get_loc(ctx->children[1]);
            return wrap(ast::Exp(std::move(bin)));
        }
        return visit(ctx->lAndExp());
    }

    std::any visitLAndExp(CACTParser::LAndExpContext* ctx) override {
        if (ctx->lAndExp()) {
            ast::BinaryExp bin{
                .op = ast::BinaryOp::AND,
                .left = std::make_unique<ast::Exp>(take<ast::Exp>(visit(ctx->lAndExp()))),
                .right = std::make_unique<ast::Exp>(take<ast::Exp>(visit(ctx->eqExp())))};
            bin.loc = get_loc(ctx->children[1]);
            return wrap(ast::Exp(std::move(bin)));
        }
        return visit(ctx->eqExp());
    }

    std::any visitEqExp(CACTParser::EqExpContext* ctx) override {
        if (ctx->eqExp()) {
            ast::BinaryExp bin{
                .op = (ctx->getText().find("==") != std::string::npos) ? ast::BinaryOp::EQ
                                                                       : ast::BinaryOp::NEQ,
                .left = std::make_unique<ast::Exp>(take<ast::Exp>(visit(ctx->eqExp()))),
                .right = std::make_unique<ast::Exp>(take<ast::Exp>(visit(ctx->relExp())))};
            bin.loc = get_loc(ctx->children[1]);
            return wrap(ast::Exp(std::move(bin)));
        }
        return visit(ctx->relExp());
    }

    std::any visitRelExp(CACTParser::RelExpContext* ctx) override {
        if (ctx->relExp()) {
            ast::BinaryOp op;
            auto text = ctx->children[1]->getText();
            if (text == "<")
                op = ast::BinaryOp::LT;
            else if (text == ">")
                op = ast::BinaryOp::GT;
            else if (text == "<=")
                op = ast::BinaryOp::LEQ;
            else
                op = ast::BinaryOp::GEQ;

            ast::BinaryExp bin{
                .op = op,
                .left = std::make_unique<ast::Exp>(take<ast::Exp>(visit(ctx->relExp()))),
                .right = std::make_unique<ast::Exp>(take<ast::Exp>(visit(ctx->addExp())))};
            bin.loc = get_loc(ctx->children[1]);
            return wrap(ast::Exp(std::move(bin)));
        }
        return visit(ctx->addExp());
    }

    std::any visitAddExp(CACTParser::AddExpContext* ctx) override {
        if (ctx->addExp()) {
            ast::BinaryExp bin{
                .op =
                    (ctx->children[1]->getText() == "+") ? ast::BinaryOp::ADD : ast::BinaryOp::SUB,
                .left = std::make_unique<ast::Exp>(take<ast::Exp>(visit(ctx->addExp()))),
                .right = std::make_unique<ast::Exp>(take<ast::Exp>(visit(ctx->mulExp())))};
            bin.loc = get_loc(ctx->children[1]);
            return wrap(ast::Exp(std::move(bin)));
        }
        return visit(ctx->mulExp());
    }

    std::any visitMulExp(CACTParser::MulExpContext* ctx) override {
        if (ctx->mulExp()) {
            ast::BinaryOp op;
            auto text = ctx->children[1]->getText();
            if (text == "*")
                op = ast::BinaryOp::MUL;
            else if (text == "/")
                op = ast::BinaryOp::DIV;
            else
                op = ast::BinaryOp::MOD;

            ast::BinaryExp bin{
                .op = op,
                .left = std::make_unique<ast::Exp>(take<ast::Exp>(visit(ctx->mulExp()))),
                .right = std::make_unique<ast::Exp>(take<ast::Exp>(visit(ctx->unaryExp())))};
            bin.loc = get_loc(ctx->children[1]);
            return wrap(ast::Exp(std::move(bin)));
        }
        return visit(ctx->unaryExp());
    }

    std::any visitUnaryExp(CACTParser::UnaryExpContext* ctx) override {
        if (ctx->primaryExp()) return visit(ctx->primaryExp());
        if (ctx->ID()) {
            ast::LVal lval_id;
            lval_id.name = ctx->ID()->getText();
            lval_id.loc = get_loc(ctx);
            ast::CallExp call{
                .func = std::move(lval_id),
                .args = {},
            };
            call.loc = get_loc(ctx);
            if (ctx->funcArgs()) {
                auto args = take<ast::FuncArgs>(visit(ctx->funcArgs()));
                call.args = std::move(args);
            }
            return wrap(ast::Exp(std::move(call)));
        }
        ast::UnaryOp op;
        auto text = ctx->children[0]->getText();
        if (text == "+")
            op = ast::UnaryOp::PLUS;
        else if (text == "-")
            op = ast::UnaryOp::MINUS;
        else
            op = ast::UnaryOp::NOT;

        ast::UnaryExp unary{
            .op = op, .exp = std::make_unique<ast::Exp>(take<ast::Exp>(visit(ctx->unaryExp())))};
        unary.loc = get_loc(ctx->children[0]);
        return wrap(ast::Exp(std::move(unary)));
    }

    std::any visitPrimaryExp(CACTParser::PrimaryExpContext* ctx) override {
        if (ctx->exp()) return visit(ctx->exp());
        if (ctx->lVal()) {
            ast::PrimaryExp primary(take<ast::LValExp>(visit(ctx->lVal())));
            primary.loc = get_loc(ctx);
            return wrap(ast::Exp(std::move(primary)));
        }
        if (ctx->number()) {
            ast::PrimaryExp primary(take<ast::ConstExp>(visit(ctx->number())));
            primary.loc = get_loc(ctx);
            return wrap(ast::Exp(std::move(primary)));
        }
        if (ctx->boolNumber()) {
            ast::PrimaryExp primary(take<ast::ConstExp>(visit(ctx->boolNumber())));
            primary.loc = get_loc(ctx);
            return wrap(ast::Exp(std::move(primary)));
        }
        return {};
    }

    std::any visitFuncArgs(CACTParser::FuncArgsContext* ctx) override {
        ast::FuncArgs args;
        for (auto* expCtx : ctx->exp()) {
            args.emplace_back(take<ast::Exp>(visit(expCtx)));
        }
        return wrap(std::move(args));
    }
};

namespace ast {

inline auto parse(std::istream& stream) -> std::unique_ptr<ast::CompUnit> {
    using namespace antlr4;
    ANTLRInputStream input(stream);
    CACTLexer lexer(&input);
    CommonTokenStream tokens(&lexer);
    CACTParser parser(&tokens);

    CACTErrorListener listener;
    lexer.removeErrorListeners();
    lexer.addErrorListener(&listener);
    parser.removeErrorListeners();
    parser.addErrorListener(&listener);

    ASTVisitor visitor;

    return std::unique_ptr<ast::CompUnit>(
        std::any_cast<ast::CompUnit*>(visitor.visit(parser.compUnit())));
}

}  // namespace ast