/// disclaimer: this file is generated by AI.
#pragma once
#include "backend/ir/ir.h"
#include "backend/ir/type.hpp"
#include "utils/diagnosis.hpp"
#include "utils/match.hpp"

#include <IRBaseVisitor.h>
#include <IRLexer.h>
#include <IRParser.h>
#include <algorithm>
#include <any>
#include <cstdlib>
#include <cstring>
#include <istream>
#include <memory>
#include <optional>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

namespace ir {

template <typename T> using node_ptr = std::shared_ptr<T>;

class IRConstructVisitor : public IRBaseVisitor {
public:
    IRConstructVisitor() {
        // Populate standard builtins to allow resolution during parsing
        auto addBuiltin = [&](const std::string& name, ir::type::Product params,
                              ir::type::TypeBox ret) {
            auto type = ir::type::Func(std::move(params).toBoxed(), std::move(ret)).toBoxed();
            program_.addBuiltinFunc(std::make_unique<ir::BuiltinFunc>(name, std::move(type)));
        };

        auto addPrint = [&](const std::string& name, ir::type::TypeBox param_type) {
            auto params = ir::type::Product();
            params.append(std::move(param_type));
            addBuiltin(name, std::move(params), ir::type::construct<void>());
        };

        auto addGet = [&](const std::string& name, ir::type::TypeBox ret_type) {
            addBuiltin(name, ir::type::Product(), std::move(ret_type));
        };

        addPrint("print_int", ir::type::construct<int>());
        addPrint("print_float", ir::type::construct<float>());
        addPrint("print_bool", ir::type::construct<bool>());
        addPrint("print_double", ir::type::construct<double>());

        addGet("get_int", ir::type::construct<int>());
        addGet("get_float", ir::type::construct<float>());
        addGet("get_double", ir::type::construct<double>());
    }

    auto takeProgram() && -> ir::Program {
        return std::move(program_);
    }

    template <typename T> static T take(std::any a) {
        if (a.has_value() && a.type() == typeid(T)) {
            return std::any_cast<T>(std::move(a));
        }
        throw COMPILER_ERROR(fmt::format("take failed for type {}", typeid(T).name()));
    }

    template <typename T> static T take_ptr(std::any a) {
        if (a.has_value() && a.type() == typeid(node_ptr<T>)) {
            auto ptr = std::any_cast<node_ptr<T>>(std::move(a));
            return std::move(*ptr);
        }
        throw COMPILER_ERROR(fmt::format("take_ptr failed for type {}", typeid(T).name()));
    }

    template <typename T> static std::any wrap(T&& val) {
        return std::make_any<T>(std::forward<T>(val));
    }

    template <typename T> static std::any wrap_ptr(T&& val) {
        using U = std::decay_t<T>;
        return std::make_any<node_ptr<U>>(std::make_shared<U>(std::forward<T>(val)));
    }

    std::any visitProgram(IRParser::ProgramContext* ctx) override {
        for (auto* cd : ctx->constDecl()) {
            visitConstDecl(cd);
        }
        for (auto* ld : ctx->letDecl()) {
            visitLetDecl(ld);
        }
        // First pass: pre-declare all functions to support mutual recursion and forward references
        for (auto* func_ctx : ctx->funcDecl()) {
            auto [name, ret_type, params] = extractFuncSignature(func_ctx);
            program_.addFunc(
                std::make_unique<ir::Func>(std::move(ret_type), name, std::move(params)));
        }
        // Second pass: define function bodies
        for (auto* func_ctx : ctx->funcDecl()) {
            visit(func_ctx);
        }
        return {};
    }

    std::any visitConstDecl(IRParser::ConstDeclContext* ctx) override {
        auto name = ctx->ID()->getText();
        auto type = take<ir::type::TypeBox>(visit(ctx->type()));
        auto init = take<ir::ConstexprValue>(visit(ctx->constexpr_()));
        auto alloc = ir::Alloc::constant(name, std::move(type), std::move(init));
        if (ctx->REF()) alloc->reference = true;
        if (current_func_) {
            local_symbol_map_[name] = alloc.get();
            assigned_defs_.insert(alloc.get());
            current_func_->addLocal(std::move(alloc));
        } else {
            symbol_map_[name] = alloc.get();
            program_.addGlobal(std::move(alloc));
        }
        return {};
    }

    std::any visitLetDecl(IRParser::LetDeclContext* ctx) override {
        auto name = ctx->ID()->getText();
        auto type = take<ir::type::TypeBox>(visit(ctx->type()));
        std::optional<ir::ConstexprValue> init;
        if (ctx->constexpr_()) {
            init = take<ir::ConstexprValue>(visit(ctx->constexpr_()));
        }
        bool immutable = !ctx->MUT();
        auto alloc = ir::Alloc::variable(name, std::move(type), std::move(init), immutable);
        if (ctx->REF()) alloc->reference = true;
        if (current_func_) {
            local_symbol_map_[name] = alloc.get();
            if (init.has_value()) {
                assigned_defs_.insert(alloc.get());
            }
            current_func_->addLocal(std::move(alloc));
        } else {
            symbol_map_[name] = alloc.get();
            program_.addGlobal(std::move(alloc));
        }
        return {};
    }

    std::any visitFuncDecl(IRParser::FuncDeclContext* ctx) override {
        auto name = ctx->ID()->getText();
        ir::Func* func = nullptr;
        for (auto& f : program_.funcs_) {
            if (f->name == name) {
                func = f.get();
                break;
            }
        }
        if (!func) {
            // Should not happen with visitProgram two-pass, but for robustness:
            auto [n, ret_type, params] = extractFuncSignature(ctx);
            program_.addFunc(std::make_unique<ir::Func>(std::move(ret_type), n, std::move(params)));
            func = program_.funcs_.back().get();
        }

        // If body already defined (blocks not empty), skip
        if (!func->blocks().empty()) return {};

        current_func_ = func;
        // Reset per-function state
        temp_map_.clear();
        block_map_.clear();
        local_symbol_map_.clear();
        assigned_defs_.clear();

        // Add params to local symbol map
        for (const auto& param : current_func_->params) {
            local_symbol_map_[param->name] = param.get();
            // Parameters are already initialized at function entry.
            assigned_defs_.insert(param.get());
        }

        for (auto* cd : ctx->constDecl()) {
            visitConstDecl(cd);
        }
        for (auto* ld : ctx->letDecl()) {
            visit(ld);
        }

        // Pre-create blocks to allow forward jumps
        for (auto* block_ctx : ctx->block()) {
            auto label = block_ctx->label()->ID()->getText();
            block_map_[label] = current_func_->newBlock(label);
        }

        for (auto* block_ctx : ctx->block()) {
            visit(block_ctx);
        }

        current_func_ = nullptr;
        return {};
    }

    auto extractFuncSignature(IRParser::FuncDeclContext* ctx)
        -> std::tuple<std::string, ir::type::TypeBox, std::vector<std::unique_ptr<ir::Alloc>>> {
        auto name = ctx->ID()->getText();
        ir::type::TypeBox ret_type = ir::type::construct<void>();
        if (ctx->type()) {
            ret_type = take<ir::type::TypeBox>(visit(ctx->type()));
        }
        std::vector<std::unique_ptr<ir::Alloc>> params;
        if (ctx->paramList()) {
            params = take_ptr<std::vector<std::unique_ptr<ir::Alloc>>>(visit(ctx->paramList()));
        }
        return {name, std::move(ret_type), std::move(params)};
    }

    std::any visitParamList(IRParser::ParamListContext* ctx) override {
        std::vector<std::unique_ptr<ir::Alloc>> params;
        for (auto* param_ctx : ctx->param()) {
            params.push_back(std::unique_ptr<ir::Alloc>(take<ir::Alloc*>(visit(param_ctx))));
        }
        return wrap_ptr(std::move(params));
    }

    std::any visitParam(IRParser::ParamContext* ctx) override {
        auto name = ctx->ID()->getText();
        auto mut = ctx->MUT() != nullptr;
        auto type = take<ir::type::TypeBox>(visit(ctx->type()));
        return wrap(new ir::Alloc(name, std::move(type), false, !mut));
    }

    std::any visitBlock(IRParser::BlockContext* ctx) override {
        auto label = ctx->label()->ID()->getText();
        current_block_ = block_map_.at(label);
        for (auto* phi : ctx->phiInst()) {
            visit(phi);
        }
        for (auto* inst : ctx->inst()) {
            visit(inst);
        }
        visit(ctx->exit());
        current_block_ = nullptr;
        return {};
    }

    std::any visitStoreInst(IRParser::StoreInstContext* ctx) override {
        // var: type = %store(var, value);
        auto result = resolveDef(ctx->var(0), take<ir::type::TypeBox>(visit(ctx->type())));
        auto addr = resolveLValue(ctx->var(1));
        auto val = take<ir::Value>(visit(ctx->value()));
        current_block_->add(ir::BinaryInst{.op = ir::InstOp::STORE,
                                           .result = std::move(result),
                                           .lhs = std::move(addr),
                                           .rhs = std::move(val)});
        return {};
    }

    std::any visitCallInst(IRParser::CallInstContext* ctx) override {
        // var : type = ID ( (argList)? ) ;
        auto result = resolveDef(ctx->var(), take<ir::type::TypeBox>(visit(ctx->type())));
        auto func_name = ctx->name()->ID()->getText();
        auto func_def = resolveFunc(func_name);
        if (!func_def)
            throw SemanticError(get_loc(ctx), fmt::format("Function {} not found", func_name));
        std::vector<ir::Value> args;
        if (ctx->argList()) {
            args = take_ptr<std::vector<ir::Value>>(visit(ctx->argList()));
        }
        current_block_->add(ir::CallInst{.result = std::move(result),
                                         .func = ir::NamedValue{func_def->first, func_def->second},
                                         .args = std::move(args)});
        return {};
    }

    std::any visitLoadElemInst(IRParser::LoadElemInstContext* ctx) override {
        // var : type = base [ index ] ;
        auto result = resolveDef(ctx->var(), take<ir::type::TypeBox>(visit(ctx->type())));
        auto base = take<ir::Value>(visit(ctx->value(0)));
        auto index = take<ir::Value>(visit(ctx->value(1)));
        current_block_->add(ir::BinaryInst{.op = ir::InstOp::LOAD_ELEM,
                                           .result = std::move(result),
                                           .lhs = std::move(base),
                                           .rhs = std::move(index)});
        return {};
    }

    std::any visitBorrowInst(IRParser::BorrowInstContext* ctx) override {
        // var : type = & MUT? var ;
        auto result = resolveDef(ctx->var(0), take<ir::type::TypeBox>(visit(ctx->type())));
        auto operand = resolveLValue(ctx->var(1));
        current_block_->add(
            ir::UnaryInst{.op = ctx->MUT() ? ir::UnaryInstOp::BORROW_MUT : ir::UnaryInstOp::BORROW,
                          .result = std::move(result),
                          .operand = ir::Value(std::move(operand))});
        return {};
    }

    std::any visitBorrowElemInst(IRParser::BorrowElemInstContext* ctx) override {
        // var : type = & MUT? var [ value ] ;
        auto result = resolveDef(ctx->var(0), take<ir::type::TypeBox>(visit(ctx->type())));
        auto base = ir::Value(resolveLValue(ctx->var(1)));
        auto index = take<ir::Value>(visit(ctx->value()));
        current_block_->add(
            ir::BinaryInst{.op = ctx->MUT() ? ir::InstOp::BORROW_ELEM_MUT : ir::InstOp::BORROW_ELEM,
                           .result = std::move(result),
                           .lhs = std::move(base),
                           .rhs = std::move(index)});
        return {};
    }

    std::any visitLoadInst(IRParser::LoadInstContext* ctx) override {
        // var : type = *(var) ;
        auto result = resolveDef(ctx->var(0), take<ir::type::TypeBox>(visit(ctx->type())));
        auto operand = resolveLValue(ctx->var(1));
        current_block_->add(ir::UnaryInst{.op = ir::UnaryInstOp::LOAD,
                                          .result = std::move(result),
                                          .operand = ir::Value(std::move(operand))});
        return {};
    }

    std::any visitBinaryInst(IRParser::BinaryInstContext* ctx) override {
        // var : type = lhs op rhs ;
        auto result = resolveDef(ctx->var(), take<ir::type::TypeBox>(visit(ctx->type())));
        auto lhs = take<ir::Value>(visit(ctx->value(0)));
        auto rhs = take<ir::Value>(visit(ctx->value(1)));
        auto op = getBinOp(ctx->binop());
        current_block_->add(ir::BinaryInst{
            .op = op, .result = std::move(result), .lhs = std::move(lhs), .rhs = std::move(rhs)});
        return {};
    }

    std::any visitPhiInst(IRParser::PhiInstContext* ctx) override {
        // var ':' type '=' PHI '(' (label ':' value (',' label ':' value)*)? ')' ';'
        auto result = resolveDef(ctx->var(), take<ir::type::TypeBox>(visit(ctx->type())));
        ir::PhiInst phi{.result = std::move(result)};
        for (size_t i = 0; i < ctx->label().size(); ++i) {
            auto label_str = ctx->label(i)->ID()->getText();
            auto val = take<ir::Value>(visit(ctx->value(i)));
            phi.args.emplace_back(block_map_.at(label_str), std::move(val));
        }
        current_block_->add(std::move(phi));
        return {};
    }

    std::any visitUnaryInst(IRParser::UnaryInstContext* ctx) override {
        // var : type = !val | -val | val ;
        auto result = resolveDef(ctx->var(), take<ir::type::TypeBox>(visit(ctx->type())));

        bool has_not = false;
        bool has_neg = false;
        for (auto* child : ctx->children) {
            if (child->getText() == "!") has_not = true;
            if (child->getText() == "-") has_neg = true;
        }

        if (has_not) {
            auto val = take<ir::Value>(visit(ctx->value()));
            current_block_->add(ir::UnaryInst{.op = ir::UnaryInstOp::NOT,
                                              .result = std::move(result),
                                              .operand = std::move(val)});
        } else if (has_neg) {
            auto val = take<ir::Value>(visit(ctx->value()));
            current_block_->add(ir::UnaryInst{.op = ir::UnaryInstOp::NEG,
                                              .result = std::move(result),
                                              .operand = std::move(val)});
        } else {
            auto val = take<ir::Value>(visit(ctx->value()));
            current_block_->add(ir::UnaryInst{.op = ir::UnaryInstOp::MOV,
                                              .result = std::move(result),
                                              .operand = std::move(val)});
        }
        return {};
    }

    std::any visitReturnExit(IRParser::ReturnExitContext* ctx) override {
        ir::Value val = ir::ConstexprValue();  // void return
        if (ctx->value()) {
            val = take<ir::Value>(visit(ctx->value()));
        }
        current_block_->setExit(ir::ReturnExit{.exp = std::move(val)});
        return {};
    }

    std::any visitBranchExit(IRParser::BranchExitContext* ctx) override {
        auto cond = take<ir::Value>(visit(ctx->value()));
        auto true_label = ctx->label(0)->ID()->getText();
        auto false_label = ctx->label(1)->ID()->getText();
        current_block_->setExit(ir::BranchExit{.cond = std::move(cond),
                                               .true_target = block_map_.at(true_label),
                                               .false_target = block_map_.at(false_label)});
        return {};
    }

    std::any visitJumpExit(IRParser::JumpExitContext* ctx) override {
        auto label = ctx->label()->ID()->getText();
        current_block_->setExit(ir::JumpExit(block_map_.at(label)));
        return {};
    }

    std::any visitArgList(IRParser::ArgListContext* ctx) override {
        std::vector<ir::Value> args;
        for (auto* val_ctx : ctx->value()) {
            args.push_back(take<ir::Value>(visit(val_ctx)));
        }
        return wrap_ptr(std::move(args));
    }

    std::any visitPointerType(IRParser::PointerTypeContext* ctx) override {
        auto elem = take<ir::type::TypeBox>(visit(ctx->type()));
        bool readonly = ctx->MUT() == nullptr;
        return wrap(
            type::TypeBox(ir::type::Reference::pointer(std::move(elem), readonly).toBoxed()));
    }

    std::any visitSliceType(IRParser::SliceTypeContext* ctx) override {
        auto elem = take<ir::type::TypeBox>(visit(ctx->type()));
        bool readonly = ctx->MUT() == nullptr;
        return wrap(type::TypeBox(ir::type::Reference::slice(std::move(elem), readonly).toBoxed()));
    }

    std::any visitArrayType(IRParser::ArrayTypeContext* ctx) override {
        auto elem = take<ir::type::TypeBox>(visit(ctx->type()));
        size_t size = std::stoul(ctx->INT_LITERAL()->getText());
        return wrap(type::TypeBox(ir::type::Array(std::move(elem), size).toBoxed()));
    }

    std::any visitPrimitiveType(IRParser::PrimitiveTypeContext* ctx) override {
        if (ctx->INT()) return wrap(ir::type::construct<int>());
        if (ctx->FLOAT()) return wrap(ir::type::construct<float>());
        if (ctx->DOUBLE()) return wrap(ir::type::construct<double>());
        if (ctx->BOOL()) return wrap(ir::type::construct<bool>());
        return wrap(ir::type::construct<void>());
    }

    std::any visitProductType(IRParser::ProductTypeContext* ctx) override {
        ir::type::Product prod;
        for (auto* t : ctx->type()) {
            prod.append(take<ir::type::TypeBox>(visit(t)));
        }
        return wrap(type::TypeBox(std::move(prod).toBoxed()));
    }

    std::any visitSumType(IRParser::SumTypeContext* ctx) override {
        std::vector<ir::type::TypeBox> items;
        for (auto* t : ctx->type()) {
            items.push_back(take<ir::type::TypeBox>(visit(t)));
        }
        return wrap(type::TypeBox(ir::type::Sum(std::move(items)).toBoxed()));
    }

    std::any visitConstexpr(IRParser::ConstexprContext* ctx) override {
        if (ctx->basicConstexpr().size() > 1 || ctx->getText().find('{') != std::string::npos) {
            // array literal
            std::vector<ir::ConstexprValue> elements;
            for (auto* bc : ctx->basicConstexpr()) {
                elements.push_back(take<ir::ConstexprValue>(visit(bc)));
            }
            if (elements.empty()) return wrap(ir::ConstexprValue());
            auto elem_type = elements[0].type;
            size_t elem_size = ir::type::size_of(elem_type);
            auto buf = std::make_unique<std::byte[]>(elem_size * elements.size());
            for (size_t i = 0; i < elements.size(); ++i) {
                match(
                    elements[i].val,
                    [&](const std::unique_ptr<std::byte[]>& v) {
                        if (v) std::memcpy(buf.get() + i * elem_size, v.get(), elem_size);
                    },
                    [&](auto& v) {
                        using V = std::decay_t<decltype(v)>;
                        if constexpr (std::is_arithmetic_v<V>) {
                            std::memcpy(buf.get() + i * elem_size, &v, elem_size);
                        }
                    });
            }
            return wrap(ir::ConstexprValue(
                std::move(ir::type::Array(std::move(elem_type), elements.size())).toBoxed(),
                std::move(buf)));
        }
        return visit(ctx->basicConstexpr(0));
    }

    std::any visitBasicConstexpr(IRParser::BasicConstexprContext* ctx) override {
        bool neg = ctx->children[0]->getText() == "-";
        if (ctx->INT_LITERAL()) {
            int val = std::stoi(ctx->INT_LITERAL()->getText(), nullptr, 0);
            return wrap(ir::ConstexprValue(neg ? -val : val));
        }
        if (ctx->FLOAT_LITERAL()) {
            float val = std::stof(ctx->FLOAT_LITERAL()->getText());
            return wrap(ir::ConstexprValue(neg ? -val : val));
        }
        if (ctx->DOUBLE_LITERAL()) {
            double val = std::stod(ctx->DOUBLE_LITERAL()->getText());
            return wrap(ir::ConstexprValue(neg ? -val : val));
        }
        if (ctx->TRUE()) return wrap(ir::ConstexprValue(true));
        if (ctx->FALSE()) return wrap(ir::ConstexprValue(false));
        return wrap(ir::ConstexprValue());
    }

    std::any visitValue(IRParser::ValueContext* ctx) override {
        if (ctx->var()) return wrap(ir::Value(resolveLValue(ctx->var())));
        if (ctx->constexpr_())
            return wrap(ir::Value(take<ir::ConstexprValue>(visit(ctx->constexpr_()))));
        return {};
    }

    std::any visitVar(IRParser::VarContext* ctx) override {
        return wrap(resolveLValue(ctx));
    }

    std::any visitTemp(IRParser::TempContext* ctx) override {
        int id = std::stoi(ctx->INT_LITERAL()->getText());
        if (temp_map_.count(id)) {
            size_t internal_id = temp_map_.at(id);
            return wrap(ir::TempValue{.type = current_func_->temps()[internal_id].type,
                                      .id = internal_id,
                                      .func = current_func_});
        }
        throw SemanticError(get_loc(ctx), fmt::format("Temporary %{} used before definition", id));
    }

private:
    ir::Program program_;
    ir::Func* current_func_{nullptr};
    ir::Block* current_block_{nullptr};

    static Location get_loc(antlr4::ParserRuleContext* ctx) {
        if (!ctx || !ctx->start) return {};
        return {static_cast<int>(ctx->start->getLine()),
                static_cast<int>(ctx->start->getCharPositionInLine())};
    }

    std::unordered_map<std::string, const ir::Alloc*> symbol_map_;        // globals
    std::unordered_map<std::string, const ir::Alloc*> local_symbol_map_;  // locals/params
    std::unordered_map<int, size_t> temp_map_;                            // %N -> internal id
    std::unordered_map<std::string, ir::Block*> block_map_;               // label -> block
    std::unordered_set<const ir::Alloc*> assigned_defs_;                  // SSA assigned defs

    auto resolveLValue(IRParser::VarContext* ctx) -> ir::LeftValue {
        if (ctx->temp()) {
            int id = std::stoi(ctx->temp()->INT_LITERAL()->getText());
            if (temp_map_.count(id)) {
                size_t internal_id = temp_map_.at(id);
                return ir::TempValue{.type = current_func_->temps()[internal_id].type,
                                     .id = internal_id,
                                     .func = current_func_};
            }
            throw SemanticError(get_loc(ctx),
                                fmt::format("Temporary %{} used before definition", id));
        } else if (ctx->ssa()) {
            auto ssa_ctx = ctx->ssa();
            auto name = ssa_ctx->ID()->getText();
            size_t version = std::stoul(ssa_ctx->INT_LITERAL()->getText());
            const ir::Alloc* alloc = nullptr;
            if (local_symbol_map_.count(name)) {
                alloc = local_symbol_map_.at(name);
            } else if (symbol_map_.count(name)) {
                alloc = symbol_map_.at(name);
            } else {
                throw SemanticError(get_loc(ssa_ctx),
                                    fmt::format("Symbol {} for SSA value not found", name));
            }
            return ir::SSAValue(alloc->type, alloc, version);
        } else {
            auto name = ctx->name()->ID()->getText();
            if (local_symbol_map_.count(name)) {
                return local_symbol_map_.at(name)->value();
            }
            if (symbol_map_.count(name)) {
                return symbol_map_.at(name)->value();
            }
            throw SemanticError(get_loc(ctx), fmt::format("Symbol {} not found", name));
        }
    }

    auto resolveDef(IRParser::VarContext* ctx, const ir::type::TypeBox& type) -> ir::LeftValue {
        if (ctx->temp()) {
            int id = std::stoi(ctx->temp()->INT_LITERAL()->getText());
            if (temp_map_.count(id)) {
                throw SemanticError(get_loc(ctx), fmt::format("Temporary %{} redefined", id));
            }
            auto temp = current_func_->newTemp(type, current_block_);
            temp_map_[id] = temp.id;
            return temp;
        } else if (ctx->ssa()) {
            auto ssa_ctx = ctx->ssa();
            auto name = ssa_ctx->ID()->getText();
            size_t version = std::stoul(ssa_ctx->INT_LITERAL()->getText());
            const ir::Alloc* alloc = nullptr;
            if (local_symbol_map_.count(name)) {
                alloc = local_symbol_map_.at(name);
            } else if (symbol_map_.count(name)) {
                alloc = symbol_map_.at(name);
            } else {
                throw SemanticError(get_loc(ssa_ctx),
                                    fmt::format("Symbol {} for SSA value not found", name));
            }
            return ir::SSAValue(type, alloc, version);
        } else {
            auto name = ctx->name()->ID()->getText();
            // ID must be pre-defined in localDecl or paramList or be a global
            if (local_symbol_map_.count(name)) {
                auto* alloc = local_symbol_map_.at(name);
                if (alloc->immutable && assigned_defs_.count(alloc)) {
                    throw SemanticError(get_loc(ctx),
                                        fmt::format("Immutable variable `{}` reassigned", name));
                }
                assigned_defs_.insert(alloc);
                return alloc->value();
            }
            if (symbol_map_.count(name)) {
                auto* alloc = symbol_map_.at(name);
                if (alloc->immutable && assigned_defs_.count(alloc)) {
                    throw SemanticError(get_loc(ctx),
                                        fmt::format("Immutable variable `{}` reassigned", name));
                }
                assigned_defs_.insert(alloc);
                return alloc->value();
            }
            throw SemanticError(
                get_loc(ctx),
                fmt::format("Variable `{}` must be declared before use as a target", name));
        }
    }

    auto resolveFunc(const std::string& name)
        -> std::optional<std::pair<ir::type::TypeBox, ir::NameDef>> {
        using T = std::pair<ir::type::TypeBox, ir::NameDef>;
        try {
            const auto& func = program_.findFunc(name);
            auto params = ir::type::Product();
            for (const auto& p : func.params) params.append(p->type);
            return std::make_optional<T>(
                {ir::type::Func(std::move(params).toBoxed(), func.ret_type).toBoxed(),
                 (const ir::Func*)&func});
        } catch (...) {
            // Check builtins in our program
            for (const auto& bf : program_.builtins()) {
                if (bf->name == name) {
                    return std::make_optional<T>({bf->type, bf.get()});
                }
            }
            return std::nullopt;
        }
    }

    auto getBinOp(IRParser::BinopContext* ctx) -> ir::InstOp {
        auto t = ctx->getText();
        if (t == "*") return ir::InstOp::MUL;
        if (t == "/") return ir::InstOp::DIV;
        if (t == "%") return ir::InstOp::MOD;
        if (t == "+") return ir::InstOp::ADD;
        if (t == "-") return ir::InstOp::SUB;
        if (t == "<=") return ir::InstOp::LEQ;
        if (t == ">=") return ir::InstOp::GEQ;
        if (t == "<") return ir::InstOp::LT;
        if (t == ">") return ir::InstOp::GT;
        if (t == "==") return ir::InstOp::EQ;
        if (t == "!=") return ir::InstOp::NEQ;
        if (t == "&&") return ir::InstOp::AND;
        if (t == "||") return ir::InstOp::OR;
        throw COMPILER_ERROR(fmt::format("Unknown binary op {}", t));
    }
};

class IRErrorListener : public antlr4::BaseErrorListener {
public:
    void syntaxError(antlr4::Recognizer* recognizer, antlr4::Token* offendingSymbol, size_t line,
                     size_t charPositionInLine, const std::string& msg,
                     std::exception_ptr e) override {
        if (dynamic_cast<antlr4::Lexer*>(recognizer)) {
            throw LexicalError(Location{(int)line, (int)charPositionInLine}, msg);
        } else {
            throw SyntacticError(Location{(int)line, (int)charPositionInLine}, msg);
        }
    }
};

auto parse(std::istream& input) -> ir::Program {
    using namespace antlr4;
    ANTLRInputStream input_stream(input);
    IRLexer lexer(&input_stream);
    CommonTokenStream tokens(&lexer);
    IRParser parser(&tokens);
    IRErrorListener error_listener;
    lexer.removeErrorListeners();
    lexer.addErrorListener(&error_listener);
    parser.removeErrorListeners();
    parser.addErrorListener(&error_listener);
    auto tree = parser.program();
    IRConstructVisitor visitor;
    visitor.visit(tree);
    return std::move(visitor).takeProgram();
}

}  // namespace ir